### ISSUE TITLE
需要升级版本了

### ISSUE THREAD

**Issue by biaowork** [qq1057119720/flutter_switch_plus#1]
升级到最新2.5 版本后，出错啦，版主好人赶紧升级一下吧

.1/lib/src/plus_switch_widget.dart:236:17: Error: Type 'ActionFactory' not found.
  Map<LocalKey, ActionFactory> _actionMap;
                ^^^^^^^^^^^^^
../../WorkItem/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_switch_plus-0.0.1/lib/src/plus_switch_widget.dart:483:29: Error: Type 'RenderToggleable' not found.
class _RenderSwitch extends RenderToggleable {
........

**Comment by qq1057119720** [comment]
已更新
